services:
  db:
    build: .
    container_name: primeEdu-db
    ports:
      - "5432:5432"
    volumes:
      - ./db_primeEdu.sql:/docker-entrypoint-initdb.d/db_primeEdu.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: primeEdu
    restart: always

volumes:
  postgres_data: